In [76]:
import numpy as np

In [77]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [78]:
np.array(my_list)

array([1, 2, 3])

In [79]:
my_mat = [[1,2,3], [4,5,6,], [7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [80]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [83]:
np.zeros(3)

array([0., 0., 0.])

In [84]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [85]:
np.ones(3)

array([1., 1., 1.])

In [86]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [87]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [88]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [89]:
np.random.rand(5)

array([0.38387061, 0.5136212 , 0.65147493, 0.94925955, 0.92692911])

In [90]:
np.random.rand(2,3)

array([[0.73245684, 0.09872624, 0.28822561],
       [0.58446916, 0.13825612, 0.60092773]])

In [91]:
np.random.randn(2)

array([-0.1712364 , -0.59655085])

In [92]:
np.random.randn(4,4)

array([[ 1.70329846,  1.61754405,  1.40339114, -0.62512037],
       [-1.1868846 ,  0.77885147,  0.36181567, -0.1361747 ],
       [-0.9709395 , -0.14642745, -2.46186505, -1.41824528],
       [-0.54589447,  0.83419386,  0.25023535, -1.67032257]])

In [93]:
np.random.randint(0,101, 5)

array([37, 13, 41, 31, 55])

In [94]:
arr = np.arange(25)

In [95]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [96]:
ranarr = np.random.randint(0,50,10)

In [97]:
ranarr

array([27, 27,  0,  9, 37, 33, 24, 31, 31, 39])

In [98]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [99]:
ranarr.max()

39

In [100]:
ranarr.min()

0

In [101]:
ranarr

array([27, 27,  0,  9, 37, 33, 24, 31, 31, 39])

In [102]:
ranarr.argmax()

9

In [103]:
ranarr.argmin()

2

In [104]:
arr = arr.reshape(5,5)

In [105]:
arr.shape

(5, 5)

In [106]:
arr.dtype

dtype('int64')