In [2]:
import numpy as np 

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [7]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
slice_of_arr = arr[0:6]

In [12]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [13]:
slice_of_arr[:] = 99

In [14]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [15]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [16]:
arr_copy = arr.copy()


In [17]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
arr_copy[:] = 100

In [20]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [21]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [26]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [32]:
arr_2d[2][1]

40

In [33]:
arr_2d[2,1]

40

In [42]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [43]:
arr = np.arange(1,11)

In [44]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
bool_arr = arr > 5

In [53]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [54]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [55]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [56]:
arr[arr<3]

array([1, 2])

In [57]:
arr_2d = np.arange(50).reshape(5,10)

In [58]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [61]:
#.     row,col
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])